namespace: stnvivanco92-dev

app:
  name: backend-data
  role: backend-data
  image: savivancofi/backend-data
  tag: v1
  replicas: 1
  containerPort: 8081
  servicePort: 8081
  createRoute: false

envFrom:
  - configMapRef:
      name: backend-data-config
  - secretRef:
      name: database-secret